name: listinha
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uno: ^1.0.1+5
  result_dart: ^1.0.5
  flutter_modular: ^6.0.0-alpha.5
  intl: ^0.18.0
  rx_notifier: 2.0.0+5
  realm: ^1.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  mocktail: ^0.3.0
  rx_notifier_generator: ^1.0.2

flutter:
  uses-material-design: true

 
